# Generated by Django 4.2.14 on 2024-08-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200)),
                ('search_engine', models.CharField(choices=[('DBLP', 'DBLP'), ('SEMANTIC_SCHOLAR', 'SEMANTIC_SCHOLAR'), ('WEB_OF_SCIENCE', 'WEB_OF_SCIENCE')], max_length=200)),
                ('paper_id', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
