# Generated by Django 4.2.14 on 2024-08-10 18:56

from django.db import migrations, models
import django.db.models.deletion
import publication.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('paper_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('paper_title', models.CharField(max_length=200)),
                ('search_string', models.CharField(max_length=200)),
                ('searched_from', models.CharField(max_length=200)),
                ('formatted_search_string', models.CharField(default='', max_length=200)),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('VALIDATED', 'VALIDATED')], default=publication.models.PublicationStatus['NEW'], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_title', models.CharField(default='', max_length=200)),
                ('doi', models.CharField(default='', max_length=200)),
                ('authors', models.CharField(default='', max_length=200)),
                ('abstract', models.TextField()),
                ('publisher', models.CharField(default='', max_length=200)),
                ('semantic_scholar_url', models.CharField(default='', max_length=200)),
                ('doi_url', models.CharField(default='', max_length=200)),
                ('publication_date', models.DateField()),
                ('field_of_study', models.CharField(default='', max_length=200)),
                ('conference_journal', models.CharField(default='', max_length=200)),
                ('publication_type', models.CharField(default='', max_length=200)),
                ('search_string', models.CharField(default='', max_length=200)),
                ('citation_count', models.IntegerField()),
                ('searched_from', models.CharField(default='', max_length=200)),
                ('publication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='publication.publication')),
            ],
        ),
        migrations.AddConstraint(
            model_name='publication',
            constraint=models.UniqueConstraint(fields=('paper_id', 'paper_title'), name='unique_paper_id_and_title'),
        ),
    ]
